"use client";

import MapGL, {
    Layer,
    NavigationControl,
    Source,
    type MapRef,
} from "react-map-gl/maplibre";
import {
    setWorkerUrl,
    type LngLatBoundsLike,
    type StyleSpecification,
} from "maplibre-gl";
import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { FeatureCollection, Point } from "geojson";
import { useTheme } from "next-themes";
import type { RouteStop, ShapeCollection } from "@/utils/types/gtfs";
import { haversine, removeOppStopPrefix } from "@/utils/helper-fn";

/**
 * MapLibre v6 loads its tile-processing worker from a URL it derives from its
 * own `import.meta.url`. A bundler content-hashes that filename, so the
 * derived path 404s and the worker never starts -- the map then renders its
 * background and silently requests no tiles.
 *
 * `scripts/copy-maplibre-worker.mjs` places the worker (and the sibling chunk
 * it imports) in `public/maplibre/`, so point MapLibre at that stable path.
 * Must happen before the first Map is constructed; module scope guarantees it.
 */
if (typeof window !== "undefined") {
    setWorkerUrl("/maplibre/maplibre-gl-worker.mjs");
}

const EMPTY_GEOJSON: ShapeCollection = {
    type: "FeatureCollection",
    features: [],
};

/**
 * Basemap. Default is OpenFreeMap "Positron": a desaturated grey-and-white
 * style with no key, no signup and no rate limit.
 *
 * Standard OSM raster was too busy -- its red/orange arterials and green parks
 * compete directly with the route colours drawn on top, so a red BRT corridor
 * disappeared into the road beneath it. Positron pushes the basemap back to
 * near-greyscale, which is the conventional choice for data overlays.
 *
 * Rejected: CARTO Positron/Voyager return HTTP 200 with an "API KEY REQUIRED"
 * watermark tile rather than a 4xx, so they look fine to a status check and
 * broken on screen. Stadia's equivalents return a real 401.
 *
 * MapTiler is still used when a key is present.
 *
 * The dark variant pairs with the app's dark mode. Note OpenFreeMap calls it
 * `dark`, not `dark-matter` -- the latter 404s.
 */
const KEY = process.env.NEXT_PUBLIC_MAPTILER_KEY;

const mapStyleFor = (dark: boolean): string =>
    KEY
        ? `https://api.maptiler.com/maps/${dark ? "dataviz-dark" : "dataviz"}/style.json?key=${KEY}`
        : `https://tiles.openfreemap.org/styles/${dark ? "dark" : "positron"}`;

/**
 * Our own SDF glyphs, generated by `scripts/build-glyphs.mjs`.
 *
 * A symbol layer can only use fonts the glyph server has rasterised, so
 * pointing `glyphs` at our own directory is what lets map labels use PT Sans
 * rather than whatever the basemap host happens to ship.
 */
const GLYPHS_URL = "/glyphs/{fontstack}/{range}.pbf";
const LABEL_FONT = ["PT Sans Narrow Bold"];

export interface DrawnLayer {
    id: string;
    color: string;
    geometry: ShapeCollection;
}

interface MainMapComponentProps {
    /** One entry per route to draw. Multiple when a stop is selected. */
    layers: DrawnLayer[];
    routeStops: RouteStop[];
    /** Every route, faint, shown only when nothing is selected. */
    overview?: ShapeCollection | null;
    /** Every station as points; GPU-rendered above `allStopsZoom`. */
    allStops?: FeatureCollection | null;
    onStationClick?: (name: string, lat: number, lon: number) => void;
    /** Fired the first time the user crosses into all-stops territory. */
    onNeedAllStops?: () => void;
    /** Pin for the currently selected station, if any. */
    activeStop?: { lat: number; lon: number; name: string } | null;
    onStopClick?: (stop: RouteStop) => void;
}

interface Cluster {
    lat: number;
    lon: number;
    count: number;
    name: string;
    /** A representative member, used to resolve the station on click. */
    stop: RouteStop;
}

/**
 * Tight bounding box around every coordinate in the route's geometry.
 * Returns null for empty geometry so callers can skip the camera move.
 */
function geometryBounds(
    geometry: ShapeCollection | null
): LngLatBoundsLike | null {
    if (!geometry?.features.length) return null;

    let minLon = Infinity;
    let minLat = Infinity;
    let maxLon = -Infinity;
    let maxLat = -Infinity;

    for (const f of geometry.features) {
        for (const [lon, lat] of f.geometry.coordinates) {
            if (!Number.isFinite(lon) || !Number.isFinite(lat)) continue;
            if (lon < minLon) minLon = lon;
            if (lat < minLat) minLat = lat;
            if (lon > maxLon) maxLon = lon;
            if (lat > maxLat) maxLat = lat;
        }
    }

    if (!Number.isFinite(minLon) || !Number.isFinite(minLat)) return null;

    return [
        [minLon, minLat],
        [maxLon, maxLat],
    ];
}

/**
 * Merges stops that share a base name and sit within `nearbyThreshold` metres,
 * so a stop and its "Sbr." (across-the-road) twin render as one pin.
 *
 * Clusters are keyed by index rather than by a stringified coordinate, so the
 * running centroid is what gets rendered -- and a comma in a stop name can
 * never corrupt the key.
 */
function clusterStops(stops: RouteStop[], nearbyThreshold: number): Cluster[] {
    const clusters: Cluster[] = [];

    for (const stop of stops) {
        const name = removeOppStopPrefix(stop.stop_name);
        const lat = stop.stop_lat;
        const lon = stop.stop_lon;

        let merged = false;
        for (const c of clusters) {
            if (c.name !== name) continue;
            if (haversine(lat, lon, c.lat, c.lon) >= nearbyThreshold) continue;

            c.lat = (c.lat * c.count + lat) / (c.count + 1);
            c.lon = (c.lon * c.count + lon) / (c.count + 1);
            c.count += 1;
            merged = true;
            break;
        }

        if (!merged)
            clusters.push({ lat, lon, count: 1, name, stop });
    }

    return clusters;
}

/**
 * Pins and labels for the clustered route stops, as one symbol layer.
 *
 * Previously the pins were DOM <Marker> elements sitting above the canvas.
 * MapLibre's collision engine cannot see DOM nodes, so a label could be
 * placed directly underneath a neighbouring pin -- and the pin, being an HTML
 * element, always painted on top of it.
 *
 * Drawing the pin as a circle in the same layer makes it part of the
 * collision box, so a label is pushed to a free side of *every* nearby pin,
 * and never ends up beneath one.
 */
const StopMarkers = React.memo(function StopMarkers({
    clusters,
    activeName,
    showLabels,
    textFont,
}: {
    clusters: Cluster[];
    activeName?: string | null;
    showLabels: boolean;
    textFont: string[];
}) {
    const data = useMemo<FeatureCollection>(
        () => ({
            type: "FeatureCollection",
            features: clusters.map((c) => ({
                type: "Feature",
                properties: {
                    name: c.name,
                    stop_id: c.stop.stop_id,
                    stop_name: c.stop.stop_name,
                    lat: c.stop.stop_lat,
                    lon: c.stop.stop_lon,
                    active: activeName === c.name ? 1 : 0,
                },
                geometry: { type: "Point", coordinates: [c.lon, c.lat] },
            })),
        }),
        [clusters, activeName]
    );

    return (
        <Source id="route-stops" type="geojson" data={data}>
            {/* Pin. Drawn first so the label layer can collide against it. */}
            <Layer
                id="route-stop-pin"
                type="circle"
                paint={{
                    "circle-radius": [
                        "case",
                        ["==", ["get", "active"], 1],
                        7,
                        4.5,
                    ],
                    "circle-color": [
                        "case",
                        ["==", ["get", "active"], 1],
                        "#FFFFFF",
                        "#0C1B2A",
                    ],
                    "circle-stroke-width": 2,
                    "circle-stroke-color": [
                        "case",
                        ["==", ["get", "active"], 1],
                        "#0C1B2A",
                        "#FFFFFF",
                    ],
                }}
            />
            {showLabels && (
                <Layer
                    id="route-stop-label"
                    type="symbol"
                    layout={{
                        "text-field": ["get", "name"],
                        "text-font": textFont,
                        "text-size": 11.5,
                        "text-max-width": 8,
                        // Try each position in turn until one is free.
                        "text-variable-anchor": [
                            "left",
                            "right",
                            "top",
                            "bottom",
                            "top-left",
                            "top-right",
                            "bottom-left",
                            "bottom-right",
                        ],
                        // Clears the pin drawn above at every anchor.
                        "text-radial-offset": 0.8,
                        "text-justify": "auto",
                        "text-allow-overlap": false,
                        "text-ignore-placement": false,
                        // Selected stop wins when labels compete for space.
                        "symbol-sort-key": [
                            "-",
                            0,
                            ["to-number", ["get", "active"]],
                        ],
                    }}
                    paint={{
                        "text-color": "#0C1B2A",
                        "text-halo-color": "#FFFFFF",
                        "text-halo-width": 1.6,
                    }}
                />
            )}
        </Source>
    );
});

const MainMapComponent = ({
    layers,
    routeStops,
    overview,
    allStops,
    activeStop,
    onStopClick,
    onStationClick,
    onNeedAllStops,
}: MainMapComponentProps) => {
    // Auto-fit frames a whole route at roughly z11-z13, so the old "> 12"
    // marker gate hid every stop the moment fitBounds finished. Pins are cheap
    // (tens per route, clustered) -- show them as soon as a route is framed,
    // and keep labels for when the user is actually zoomed in.
    const zoomThreshold = 10;
    // Auto-fit frames a trunk anywhere from z11.9 to z15.8 depending on how
    // long it is, so a high fixed gate hid labels on most routes right after
    // the camera settled. Collision placement already drops labels that will
    // not fit, so the gate only needs to stop the far-out view being noisy.
    const labelThreshold = 11;
    const nearbyThreshold = 55;
    /** Below this, 6,437 pins would be an unreadable smear. */
    const allStopsZoom = 14;

    const mapRef = useRef<MapRef | null>(null);

    // `resolvedTheme` collapses "system" to the actual light/dark value.
    const { resolvedTheme } = useTheme();
    const styleUrl = useMemo(
        () => mapStyleFor(resolvedTheme === "dark"),
        [resolvedTheme]
    );

    /**
     * The basemap style is fetched and its `glyphs` URL repointed at our own
     * SDF directory before handing it to MapLibre. A style carries exactly one
     * glyph endpoint for every symbol layer, so this is the only way to use
     * PT Sans without also self-hosting the basemap's own label fonts --
     * hence `scripts/build-glyphs.mjs` bakes both PT Sans Narrow Bold (ours)
     * and PT Sans Bold (the fallback the basemap layers resolve to).
     */
    const [mapStyle, setMapStyle] = useState<string | StyleSpecification>(
        styleUrl
    );

    useEffect(() => {
        let cancelled = false;

        (async () => {
            try {
                const res = await fetch(styleUrl);
                if (!res.ok) throw new Error(String(res.status));
                const style = (await res.json()) as StyleSpecification;

                // Basemap labels keep their own fonts, which our glyph
                // directory does not have -- repoint them at a stack we do
                // ship so they still render.
                for (const layer of style.layers ?? []) {
                    const l = layer as {
                        layout?: Record<string, unknown>;
                        type?: string;
                    };
                    if (l.type === "symbol" && l.layout?.["text-font"]) {
                        l.layout["text-font"] = ["PT Sans Bold"];
                    }
                }

                if (!cancelled) {
                    setMapStyle({ ...style, glyphs: GLYPHS_URL });
                }
            } catch {
                // Fall back to the untouched style: labels then use the
                // basemap's fonts rather than disappearing.
                if (!cancelled) setMapStyle(styleUrl);
            }
        })();

        return () => {
            cancelled = true;
        };
    }, [styleUrl]);

    // Uncontrolled camera (initialViewState + no `onMove` write-back) so
    // fitBounds can animate freely. A controlled viewState would be re-applied
    // by React on every frame and fight the easing.
    const [zoomLevel, setZoomLevel] = useState(10);

    const handleMove = useCallback((e: { viewState: { zoom: number } }) => {
        // Quantise: markers only care about whole zoom steps, so this re-renders
        // ~once per zoom level instead of once per animation frame.
        setZoomLevel((prev) => {
            const next = Math.floor(e.viewState.zoom);
            return next === prev ? prev : next;
        });
    }, []);

    // Clustering is O(n^2); keep it out of the render path on every pan.
    const routeClusters = useMemo(
        () => clusterStops(routeStops, nearbyThreshold),
        [routeStops, nearbyThreshold]
    );

    // Ask for the stop layer the first time it could actually be shown, so a
    // visitor who never zooms in never downloads it.
    useEffect(() => {
        if (zoomLevel >= allStopsZoom) onNeedAllStops?.();
    }, [zoomLevel, allStopsZoom, onNeedAllStops]);

    // Union of every drawn layer, so a multi-route stop view frames them all.
    const bounds = useMemo(() => {
        const boxes = layers
            .map((l) => geometryBounds(l.geometry))
            .filter((b): b is [[number, number], [number, number]] =>
                Boolean(b)
            );
        if (!boxes.length) return null;

        return boxes.reduce(
            (acc, b) => [
                [Math.min(acc[0][0], b[0][0]), Math.min(acc[0][1], b[0][1])],
                [Math.max(acc[1][0], b[1][0]), Math.max(acc[1][1], b[1][1])],
            ],
            boxes[0]
        ) as LngLatBoundsLike;
    }, [layers]);

    // Frame the selected route. Depends on `bounds` (not `geometry`) so
    // re-selecting a route with identical extent does not re-animate.
    useEffect(() => {
        const map = mapRef.current;
        if (!map || !bounds) return;

        map.fitBounds(bounds, {
            // Leaves room for the stop labels, which extend to the right of
            // their pin, and keeps the line clear of the zoom controls.
            padding: { top: 64, bottom: 64, left: 64, right: 96 },
            // A single stop would otherwise zoom to maxZoom.
            maxZoom: 15,
            duration: 900,
            essential: true,
        });
    }, [bounds]);

    return (
        <MapGL
            ref={mapRef}
            // Clicking a GPU circle layer: hit-test by layer id, since these
            // are painted pixels rather than DOM nodes with their own handlers.
            interactiveLayerIds={[
                ...(routeClusters.length ? ["route-stop-pin"] : []),
                ...(allStops && zoomLevel >= allStopsZoom
                    ? ["all-stops-circle"]
                    : []),
            ]}
            onClick={(e) => {
                const f = e.features?.[0];
                if (!f) return;

                // Route stops carry the original stop, so the panel can
                // resolve the station exactly as a marker click used to.
                if (f.layer?.id === "route-stop-pin") {
                    const p = f.properties ?? {};
                    onStopClick?.({
                        stop_id: String(p.stop_id ?? ""),
                        stop_name: String(p.stop_name ?? p.name ?? ""),
                        stop_lat: Number(p.lat),
                        stop_lon: Number(p.lon),
                        sequence: 0,
                    });
                    return;
                }

                if (f.layer?.id === "all-stops-circle") {
                    const [lon, lat] = (f.geometry as Point).coordinates;
                    onStationClick?.(
                        String(f.properties?.name ?? ""),
                        lat,
                        lon
                    );
                }
            }}
            cursor={"auto"}
            initialViewState={{
                latitude: -6.1907,
                longitude: 106.8228,
                zoom: 10,
            }}
            onMove={handleMove}
            // Fills whatever the parent allots. A hard 100vh would overflow the
            // mobile layout, where the map shares the screen with a bottom sheet.
            style={{ width: "100%", height: "100%" }}
            mapStyle={mapStyle}
        >
            <NavigationControl position="bottom-right" />

            {/*
              The whole network, faint, as context. One GPU-rendered GeoJSON
              source -- not 240 React layers. Hidden once a route or stop is
              selected so the selection reads clearly.
            */}
            {overview && layers.length === 0 && (
                <Source id="overview" type="geojson" data={overview}>
                    <Layer
                        id="overview-line"
                        type="line"
                        layout={{ "line-join": "round", "line-cap": "round" }}
                        paint={{
                            // Colour travels in the feature, so all 700 lines
                            // stay a single draw call.
                            "line-color": ["get", "color"],
                            "line-opacity": 0.35,
                            // Thinner when zoomed out, where lines bunch up.
                            "line-width": [
                                "interpolate",
                                ["linear"],
                                ["zoom"],
                                9,
                                1,
                                13,
                                2.5,
                            ],
                        }}
                    />
                </Source>
            )}

            {/* A Source per route so each keeps its own colour. */}
            {layers.length === 0 ? (
                <Source id="shape-empty" type="geojson" data={EMPTY_GEOJSON}>
                    <Layer id="shape-line" type="line" />
                </Source>
            ) : (
                layers.map((l) => (
                    <Source
                        key={l.id}
                        id={`shape-${l.id}`}
                        type="geojson"
                        data={l.geometry}
                    >
                        <Layer
                            id={`shape-line-${l.id}`}
                            type="line"
                            layout={{
                                "line-join": "round",
                                "line-cap": "round",
                            }}
                            paint={{
                                "line-color": `#${l.color}`,
                                "line-width": 3,
                                // Slight transparency so overlapping corridors
                                // stay legible when many routes share a street.
                                "line-opacity": layers.length > 1 ? 0.75 : 1,
                            }}
                        />
                    </Source>
                ))
            )}

            {/*
              All stops, GPU-rendered. Only above `allStopsZoom`, where pins
              are far enough apart to read. 6,437 DOM markers would instead be
              6,437 React components plus an O(n^2) clustering pass.
            */}
            {allStops && zoomLevel >= allStopsZoom && (
                <Source id="all-stops" type="geojson" data={allStops}>
                    <Layer
                        id="all-stops-circle"
                        type="circle"
                        paint={{
                            "circle-radius": [
                                "interpolate",
                                ["linear"],
                                ["zoom"],
                                14,
                                2.5,
                                17,
                                5,
                            ],
                            "circle-color": "#0C1B2A",
                            "circle-stroke-width": 1.5,
                            "circle-stroke-color": "#FFFFFF",
                            "circle-opacity": 0.9,
                        }}
                    />
                    <Layer
                        id="all-stops-label"
                        type="symbol"
                        minzoom={15}
                        layout={{
                            "text-field": ["get", "name"],
                            "text-font": LABEL_FONT,
                            "text-size": 11,
                            "text-max-width": 8,
                            // Same dodge-then-hide behaviour as the route
                            // labels, rather than a fixed offset below the pin.
                            "text-variable-anchor": [
                                "left",
                                "right",
                                "top",
                                "bottom",
                                "top-left",
                                "top-right",
                                "bottom-left",
                                "bottom-right",
                            ],
                            "text-radial-offset": 0.8,
                            "text-justify": "auto",
                            "text-allow-overlap": false,
                            // Busier interchanges win when labels collide.
                            "symbol-sort-key": ["-", 0, ["get", "routes"]],
                        }}
                        paint={{
                            "text-color": "#0C1B2A",
                            "text-halo-color": "#FFFFFF",
                            "text-halo-width": 1.5,
                        }}
                    />
                </Source>
            )}

            {zoomLevel > zoomThreshold && routeClusters.length > 0 && (
                <StopMarkers
                    clusters={routeClusters}
                    activeName={activeStop?.name ?? null}
                    showLabels={zoomLevel >= labelThreshold}
                    textFont={LABEL_FONT}
                />
            )}
        </MapGL>
    );
};

export default MainMapComponent;
