"use client";

import MapGL, {
    Layer,
    NavigationControl,
    Popup,
    Source,
    type MapRef,
} from "react-map-gl/maplibre";
import {
    setWorkerUrl,
    type ExpressionSpecification,
    type LngLatBoundsLike,
    type StyleSpecification,
    type VariableAnchorOffsetCollectionSpecification,
} from "maplibre-gl";
import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { FeatureCollection, Point } from "geojson";
import { useTheme } from "next-themes";
import type { RouteStop, ShapeCollection } from "@/utils/types/gtfs";
import { haversine, removeOppStopPrefix } from "@/utils/helper-fn";

/**
 * MapLibre v6 loads its tile-processing worker from a URL it derives from its
 * own `import.meta.url`. A bundler content-hashes that filename, so the
 * derived path 404s and the worker never starts -- the map then renders its
 * background and silently requests no tiles.
 *
 * `scripts/copy-maplibre-worker.mjs` places the worker (and the sibling chunk
 * it imports) in `public/maplibre/`, so point MapLibre at that stable path.
 * Must happen before the first Map is constructed; module scope guarantees it.
 */
if (typeof window !== "undefined") {
    setWorkerUrl("/maplibre/maplibre-gl-worker.mjs");
}

const EMPTY_GEOJSON: ShapeCollection = {
    type: "FeatureCollection",
    features: [],
};

/**
 * Basemap. Default is OpenFreeMap "Positron": a desaturated grey-and-white
 * style with no key, no signup and no rate limit.
 *
 * Standard OSM raster was too busy -- its red/orange arterials and green parks
 * compete directly with the route colours drawn on top, so a red BRT corridor
 * disappeared into the road beneath it. Positron pushes the basemap back to
 * near-greyscale, which is the conventional choice for data overlays.
 *
 * Rejected: CARTO Positron/Voyager return HTTP 200 with an "API KEY REQUIRED"
 * watermark tile rather than a 4xx, so they look fine to a status check and
 * broken on screen. Stadia's equivalents return a real 401.
 *
 * MapTiler is still used when a key is present.
 *
 * The dark variant pairs with the app's dark mode. Note OpenFreeMap calls it
 * `dark`, not `dark-matter` -- the latter 404s.
 */
const KEY = process.env.NEXT_PUBLIC_MAPTILER_KEY;

const mapStyleFor = (dark: boolean): string =>
    KEY
        ? `https://api.maptiler.com/maps/${dark ? "dataviz-dark" : "dataviz"}/style.json?key=${KEY}`
        : `https://tiles.openfreemap.org/styles/${dark ? "dark" : "positron"}`;

/**
 * Our own SDF glyphs, generated by `scripts/build-glyphs.mjs`.
 *
 * A symbol layer can only use fonts the glyph server has rasterised, so
 * pointing `glyphs` at our own directory is what lets map labels use PT Sans
 * rather than whatever the basemap host happens to ship.
 */
const GLYPHS_URL = "/glyphs/{fontstack}/{range}.pbf";
const LABEL_FONT = ["PT Sans Narrow Bold"];

/**
 * Pin images, registered with the map so the stop marker can be an *icon of
 * the symbol layer* rather than a separate circle layer.
 *
 * This matters for placement: MapLibre's collision engine only considers
 * symbols. A circle layer contributes no collision box, so labels happily sat
 * underneath neighbouring pins. Once the pin is `icon-image` on the same
 * symbol, its box is part of the symbol and `text-variable-anchor` moves the
 * label clear of every pin, not just of other labels.
 */
function makeDotImage(
    { r, stroke, fill, ring }: DotSpec,
    pixelRatio = 2
): ImageData {
    const size = Math.ceil((r + stroke) * 2 * pixelRatio);
    const c = document.createElement("canvas");
    c.width = size;
    c.height = size;

    const ctx = c.getContext("2d")!;
    ctx.scale(pixelRatio, pixelRatio);

    const mid = size / pixelRatio / 2;
    ctx.beginPath();
    ctx.arc(mid, mid, r, 0, Math.PI * 2);
    ctx.fillStyle = fill;
    ctx.fill();
    ctx.lineWidth = stroke;
    ctx.strokeStyle = ring;
    ctx.stroke();

    return ctx.getImageData(0, 0, size, size);
}

interface DotSpec {
    r: number;
    stroke: number;
    fill: string;
    ring: string;
}

/**
 * Every pin image the map registers, keyed by the id the layers refer to.
 *
 * `all-stop-dot` is drawn small and scaled up by `icon-size`; a single image
 * reused across the zoom range beats registering one per zoom step.
 */
const PIN_IMAGES: Record<string, DotSpec> = {
    "stop-pin": { r: 5, stroke: 2, fill: "#0C1B2A", ring: "#FFFFFF" },
    "stop-pin-active": { r: 7, stroke: 2, fill: "#FFFFFF", ring: "#0C1B2A" },
    // Drawn at the size it has when `icon-size` is 1, then scaled per zoom.
    "all-stop-dot": { r: 5, stroke: 2, fill: "#0C1B2A", ring: "#FFFFFF" },
    // Hover: same geometry, inverted like the active route pin so the cursor
    // target is unmistakable.
    "all-stop-dot-hover": { r: 6, stroke: 2, fill: "#FFFFFF", ring: "#0C1B2A" },
    "stop-pin-hover": { r: 6, stroke: 2, fill: "#FFFFFF", ring: "#0C1B2A" },
};

/**
 * The blocker icon: a fully transparent square whose only job is to occupy a
 * collision box the width of the drawn route line (3px) plus a little margin.
 */
function makeBlockerImage(size = 9, pixelRatio = 2): ImageData {
    const px = Math.ceil(size * pixelRatio);
    const c = document.createElement("canvas");
    c.width = px;
    c.height = px;
    return c.getContext("2d")!.getImageData(0, 0, px, px);
}

export interface DrawnLayer {
    id: string;
    color: string;
    geometry: ShapeCollection;
}

interface MainMapComponentProps {
    /** One entry per route to draw. Multiple when a stop is selected. */
    layers: DrawnLayer[];
    routeStops: RouteStop[];
    /** Every route, faint, shown only when nothing is selected. */
    overview?: ShapeCollection | null;
    /** Every station as points; GPU-rendered above `allStopsZoom`. */
    allStops?: FeatureCollection | null;
    onStationClick?: (name: string, lat: number, lon: number) => void;
    /** Fired the first time the user crosses into all-stops territory. */
    onNeedAllStops?: () => void;
    /** Pin for the currently selected station, if any. */
    activeStop?: { lat: number; lon: number; name: string } | null;
    onStopClick?: (stop: RouteStop) => void;
    /**
     * Clicking the map away from any stop. Used to dismiss the open station
     * without reaching for the sidebar.
     */
    onBackgroundClick?: () => void;
    /**
     * Rendered inside a popup anchored to `activeStop`. Lets the page own the
     * station card's content while the map owns its placement.
     */
    stopPopup?: React.ReactNode;
}

interface Cluster {
    lat: number;
    lon: number;
    count: number;
    name: string;
    /** A representative member, used to resolve the station on click. */
    stop: RouteStop;
}

/**
 * Tight bounding box around every coordinate in the route's geometry.
 * Returns null for empty geometry so callers can skip the camera move.
 */
function geometryBounds(
    geometry: ShapeCollection | null
): LngLatBoundsLike | null {
    if (!geometry?.features.length) return null;

    let minLon = Infinity;
    let minLat = Infinity;
    let maxLon = -Infinity;
    let maxLat = -Infinity;

    for (const f of geometry.features) {
        for (const [lon, lat] of f.geometry.coordinates) {
            if (!Number.isFinite(lon) || !Number.isFinite(lat)) continue;
            if (lon < minLon) minLon = lon;
            if (lat < minLat) minLat = lat;
            if (lon > maxLon) maxLon = lon;
            if (lat > maxLat) maxLat = lat;
        }
    }

    if (!Number.isFinite(minLon) || !Number.isFinite(minLat)) return null;

    return [
        [minLon, minLat],
        [maxLon, maxLat],
    ];
}

/**
 * The eight variable anchors as unit vectors, in MapLibre's offset
 * convention: +x pushes the label right of the pin, +y pushes it *down*.
 *
 * `evaluateVariableOffset` in MapLibre derives these from `text-radial-offset`
 * itself, splitting diagonals by 1/sqrt2 so every anchor sits on a circle of
 * the same radius. We reproduce that here because we need to reorder the
 * anchors per feature, which `text-radial-offset` cannot express.
 */
const SQRT1_2 = Math.SQRT1_2;
const ANCHOR_UNITS: Record<string, [number, number]> = {
    left: [1, 0],
    right: [-1, 0],
    top: [0, 1],
    bottom: [0, -1],
    "top-left": [SQRT1_2, SQRT1_2],
    "top-right": [-SQRT1_2, SQRT1_2],
    "bottom-left": [SQRT1_2, -SQRT1_2],
    "bottom-right": [-SQRT1_2, -SQRT1_2],
};

/**
 * Anchor candidates per route bearing, perpendicular to the line first.
 *
 * The collision engine cannot see line layers -- a line contributes no
 * collision box -- so no amount of `text-allow-overlap` tuning stops a label
 * from landing on the route. The fix is to stop *offering* the bad anchors:
 * MapLibre walks this array in order and takes the first that fits.
 *
 * Each row therefore (a) leads with the two anchors perpendicular to the line
 * and (b) omits the two that run *along* it. A label offset parallel to the
 * line sits at the line's own screen position, so those anchors are never an
 * acceptable answer -- offering them as a fallback is what still produced a
 * struck-through label once a neighbouring label took the good side. With
 * them gone the label either finds a clear side or is dropped, and
 * `text-optional` keeps the pin either way.
 *
 * Index is the quantised bearing of the line through the stop:
 *   0 = E-W line   -> prefer top/bottom,          never left/right
 *   1 = NE-SW line -> prefer top-left/bottom-right, never top-right/bottom-left
 *   2 = N-S line   -> prefer left/right,          never top/bottom
 *   3 = NW-SE line -> prefer top-right/bottom-left, never top-left/bottom-right
 */
const ANCHOR_ORDER: string[][] = [
    ["top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right"],
    ["top-left", "bottom-right", "top", "bottom", "left", "right"],
    ["left", "right", "top-left", "bottom-left", "top-right", "bottom-right"],
    ["top-right", "bottom-left", "top", "bottom", "left", "right"],
];

/**
 * Builds the `text-variable-anchor-offset` value for one bearing bucket.
 *
 * The property supersedes `text-variable-anchor` + `text-radial-offset` (see
 * `getTextVariableAnchorOffset` upstream) and, unlike those two, is
 * data-driven -- which is the whole reason for this approach: the preferred
 * side has to vary per stop, and `text-variable-anchor` is data-constant.
 */
function anchorOffsetsFor(
    axis: number,
    radius: number
): VariableAnchorOffsetCollectionSpecification {
    return ANCHOR_ORDER[axis].flatMap((anchor) => {
        const [ux, uy] = ANCHOR_UNITS[anchor];
        return [
            anchor,
            [+(ux * radius).toFixed(3), +(uy * radius).toFixed(3)] as [
                number,
                number,
            ],
        ];
    }) as VariableAnchorOffsetCollectionSpecification;
}

/** `text-variable-anchor-offset` expression: picks an order by `axis`. */
function anchorOffsetExpression(radius: number): ExpressionSpecification {
    return [
        "match",
        ["get", "axis"],
        ...ANCHOR_ORDER.flatMap((_, i) => [
            i,
            ["literal", anchorOffsetsFor(i, radius)],
        ]),
        ["literal", anchorOffsetsFor(0, radius)],
    ] as unknown as ExpressionSpecification;
}

/**
 * Densifies route lines into points spaced ~`stepPx` apart on screen, for the
 * invisible blocker symbols that give the line a collision footprint.
 *
 * MapLibre's collision engine only indexes symbols, so a line layer is
 * invisible to it and a label will happily sit on the route. Ordering anchors
 * by bearing (above) biases placement away from the line, but cannot *stop*
 * it: where the corridor doubles back there is no clear side, and the label
 * still lands on a strand. Giving the line real collision boxes is what makes
 * "never overlap the route" enforceable rather than merely preferred.
 *
 * Spacing is in metres derived from the zoom, so the chain stays dense enough
 * to be continuous without emitting more points than the grid can index.
 */
function blockerPoints(
    shapes: ShapeCollection | null | undefined,
    zoom: number
): FeatureCollection {
    const features: FeatureCollection["features"] = [];
    if (!shapes?.features?.length) {
        return { type: "FeatureCollection", features };
    }

    // Metres per pixel at this zoom (equator); good enough for spacing.
    const mpp = 156543.03392 / Math.pow(2, zoom);
    const stepM = Math.max(8, mpp * 10);

    for (const f of shapes.features) {
        const co = f.geometry?.coordinates;
        if (!co || co.length < 2) continue;

        let carry = 0;
        for (let i = 0; i + 1 < co.length; i++) {
            const [lon1, lat1] = co[i];
            const [lon2, lat2] = co[i + 1];
            const segM = haversine(lat1, lon1, lat2, lon2);
            if (!Number.isFinite(segM) || segM === 0) continue;

            // Walk the segment, dropping a point every `stepM`.
            for (let d = carry; d < segM; d += stepM) {
                const t = d / segM;
                features.push({
                    type: "Feature",
                    properties: {},
                    geometry: {
                        type: "Point",
                        coordinates: [
                            lon1 + (lon2 - lon1) * t,
                            lat1 + (lat2 - lat1) * t,
                        ],
                    },
                });
            }
            carry = (carry - segM) % stepM;
            if (carry < 0) carry += stepM;
        }
    }

    return { type: "FeatureCollection", features };
}

/**
 * Quantises a line's local direction at `[lon, lat]` into one of the four
 * buckets above, by finding the nearest shape vertex and measuring the
 * segment through it.
 *
 * Longitude is scaled by cos(lat) so the bearing is measured in approximately
 * equal-distance space; at Jakarta's latitude the raw degree ratio would skew
 * every bearing by a few degrees, which is enough to pick the wrong bucket on
 * a near-diagonal run.
 */
function lineAxisAt(
    lon: number,
    lat: number,
    shapes: ShapeCollection | null | undefined
): number {
    if (!shapes?.features?.length) return 0;

    const kx = Math.cos((lat * Math.PI) / 180);
    let best = Infinity;
    let bx = 0;
    let by = 0;

    for (const f of shapes.features) {
        const co = f.geometry?.coordinates;
        if (!co || co.length < 2) continue;

        for (let i = 0; i < co.length; i++) {
            const dx = (co[i][0] - lon) * kx;
            const dy = co[i][1] - lat;
            const d2 = dx * dx + dy * dy;
            if (d2 >= best) continue;

            best = d2;
            // Direction of the segment spanning this vertex.
            const a = co[i === 0 ? 0 : i - 1];
            const b = co[i === co.length - 1 ? co.length - 1 : i + 1];
            bx = (b[0] - a[0]) * kx;
            by = b[1] - a[1];
        }
    }

    if (bx === 0 && by === 0) return 0;

    // Undirected line: fold to [0, 180), then quantise to 4 buckets of 45deg.
    let deg = (Math.atan2(by, bx) * 180) / Math.PI;
    if (deg < 0) deg += 180;
    return Math.round(deg / 45) % 4;
}

/**
 * Merges stops that share a base name and sit within `nearbyThreshold` metres,
 * so a stop and its "Sbr." (across-the-road) twin render as one pin.
 *
 * Clusters are keyed by index rather than by a stringified coordinate, so the
 * running centroid is what gets rendered -- and a comma in a stop name can
 * never corrupt the key.
 */
function clusterStops(stops: RouteStop[], nearbyThreshold: number): Cluster[] {
    const clusters: Cluster[] = [];

    for (const stop of stops) {
        const name = removeOppStopPrefix(stop.stop_name);
        const lat = stop.stop_lat;
        const lon = stop.stop_lon;

        let merged = false;
        for (const c of clusters) {
            if (c.name !== name) continue;
            if (haversine(lat, lon, c.lat, c.lon) >= nearbyThreshold) continue;

            c.lat = (c.lat * c.count + lat) / (c.count + 1);
            c.lon = (c.lon * c.count + lon) / (c.count + 1);
            c.count += 1;
            merged = true;
            break;
        }

        if (!merged)
            clusters.push({ lat, lon, count: 1, name, stop });
    }

    return clusters;
}

/**
 * Pins and labels for the clustered route stops, as one symbol layer.
 *
 * Previously the pins were DOM <Marker> elements sitting above the canvas.
 * MapLibre's collision engine cannot see DOM nodes, so a label could be
 * placed directly underneath a neighbouring pin -- and the pin, being an HTML
 * element, always painted on top of it.
 *
 * Drawing the pin as the symbol's own icon makes it part of the collision
 * box, so a label is pushed to a free side of *every* nearby pin, and never
 * ends up beneath one.
 */
const StopMarkers = React.memo(function StopMarkers({
    clusters,
    activeName,
    hoveredName,
    showLabels,
    textFont,
    shapes,
}: {
    clusters: Cluster[];
    activeName?: string | null;
    hoveredName?: string | null;
    showLabels: boolean;
    textFont: string[];
    /** Route geometry, so a label can be steered off the line it sits on. */
    shapes?: ShapeCollection | null;
}) {
    const data = useMemo<FeatureCollection>(
        () => ({
            type: "FeatureCollection",
            features: clusters.map((c) => ({
                type: "Feature",
                properties: {
                    name: c.name,
                    stop_id: c.stop.stop_id,
                    stop_name: c.stop.stop_name,
                    lat: c.stop.stop_lat,
                    lon: c.stop.stop_lon,
                    active: activeName === c.name ? 1 : 0,
                    axis: lineAxisAt(c.lon, c.lat, shapes),
                },
                geometry: { type: "Point", coordinates: [c.lon, c.lat] },
            })),
        }),
        [clusters, activeName, shapes]
    );

    return (
        <Source id="route-stops" type="geojson" data={data}>
            {/*
              Pin and label are ONE symbol. The icon is always drawn
              (`icon-allow-overlap`) while the text may be dropped, and because
              both belong to the same symbol the icon's box is part of what the
              label must avoid -- so a label is never placed under a pin, its
              own or a neighbour's.
            */}
            <Layer
                id="route-stop-pin"
                type="symbol"
                layout={{
                    // Active wins over hover, so the selected stop keeps its
                    // inverted look while the cursor passes over it.
                    "icon-image": [
                        "case",
                        ["==", ["get", "active"], 1],
                        "stop-pin-active",
                        ["==", ["get", "name"], hoveredName ?? "\u0000"],
                        "stop-pin-hover",
                        "stop-pin",
                    ],
                    "icon-allow-overlap": true,
                    "icon-ignore-placement": false,
                    ...(showLabels
                        ? {
                              "text-field": ["get", "name"],
                              "text-font": textFont,
                              // Integer: a fractional size lands glyph edges
                              // between texel centres, which costs sharpness
                              // at these small sizes for no visual gain.
                              "text-size": 12,
                              "text-max-width": 8,
                              // Anchors ordered per stop so the sides clear of
                              // the route line are tried first. Supersedes
                              // text-variable-anchor + text-radial-offset,
                              // which cannot vary per feature. The active pin
                              // is drawn larger (r7+2 vs r5+2), so it gets the
                              // bigger radius to clear its own icon.
                              "text-variable-anchor-offset": [
                                  "case",
                                  ["==", ["get", "active"], 1],
                                  anchorOffsetExpression(1.1),
                                  anchorOffsetExpression(0.9),
                              ],
                              "text-justify": "auto",
                              "text-allow-overlap": false,
                              "text-ignore-placement": false,
                              // Without this MapLibre treats icon and text as
                              // one placement unit (placement.ts: `placeIcon =
                              // placeText = placeIcon && placeText`), so a
                              // label that finds no free anchor takes its pin
                              // down with it. We want the pin to always stay.
                              "text-optional": true,
                              // Lower sorts first, so the active stop wins.
                              "symbol-sort-key": [
                                  "-",
                                  0,
                                  ["to-number", ["get", "active"]],
                              ],
                          }
                        : {}),
                }}
                paint={{
                    "text-color": "#0C1B2A",
                    "text-halo-color": "#FFFFFF",
                    // Collision cannot help against the route line -- line
                    // layers contribute no boxes -- so the halo is the only
                    // thing keeping a label legible where it crosses one.
                    "text-halo-width": 2,
                }}
            />
        </Source>
    );
});

const MainMapComponent = ({
    layers,
    routeStops,
    overview,
    allStops,
    activeStop,
    onStopClick,
    onBackgroundClick,
    onStationClick,
    onNeedAllStops,
    stopPopup,
}: MainMapComponentProps) => {
    // Auto-fit frames a whole route at roughly z11-z13, so the old "> 12"
    // marker gate hid every stop the moment fitBounds finished. Pins are cheap
    // (tens per route, clustered) -- show them as soon as a route is framed,
    // and keep labels for when the user is actually zoomed in.
    const zoomThreshold = 10;
    // Auto-fit frames a trunk anywhere from z11.9 to z15.8 depending on how
    // long it is, so a high fixed gate hid labels on most routes right after
    // the camera settled. Collision placement already drops labels that will
    // not fit, so the gate only needs to stop the far-out view being noisy.
    const labelThreshold = 11;
    const nearbyThreshold = 55;
    /** Below this, 6,437 pins would be an unreadable smear. */
    const allStopsZoom = 12;

    const mapRef = useRef<MapRef | null>(null);

    /**
     * Name of the all-stops dot under the cursor, or null.
     *
     * Tracked by name because that is what the layer's `icon-image` expression
     * compares against -- the dot layer carries no stable per-feature id.
     */
    const [hoveredStop, setHoveredStop] = useState<string | null>(null);
    // Incremented for every stop hit so even re-clicking the same stop asks
    // the camera to focus it again.
    const [stopFocusRequest, setStopFocusRequest] = useState(0);

    // `resolvedTheme` collapses "system" to the actual light/dark value.
    const { resolvedTheme } = useTheme();
    const isDark = resolvedTheme === "dark";
    const styleUrl = useMemo(() => mapStyleFor(isDark), [isDark]);

    /**
     * The basemap style is fetched and its `glyphs` URL repointed at our own
     * SDF directory before handing it to MapLibre. A style carries exactly one
     * glyph endpoint for every symbol layer, so this is the only way to use
     * PT Sans without also self-hosting the basemap's own label fonts --
     * hence `scripts/build-glyphs.mjs` bakes PT Sans Narrow Bold (our stop
     * labels), PT Sans Bold, and PT Sans Regular (basemap labels).
     */
    const [mapStyle, setMapStyle] = useState<string | StyleSpecification>(
        styleUrl
    );

    useEffect(() => {
        let cancelled = false;

        (async () => {
            try {
                const res = await fetch(styleUrl);
                if (!res.ok) throw new Error(String(res.status));
                const style = (await res.json()) as StyleSpecification;

                // Basemap labels are context, not content: the stop names
                // are what the user is here to read. Two things were making
                // them compete.
                //
                // 1. Weight. Every basemap label was being repointed at
                //    PT Sans *Bold* -- heavier than the basemap's own Noto
                //    Sans Regular -- so place names rendered bolder than the
                //    style intended and read as foreground.
                // 2. Contrast. Positron's place labels are near-black on a
                //    near-white map, which is the strongest contrast on
                //    screen; our stop labels could not out-rank them.
                //
                // So: Regular weight, and muted toward the background. Halos
                // stay (they keep labels legible over busy geometry) but are
                // softened to match.
                const muted = isDark ? "#8A94A6" : "#9AA3B0";
                const mutedHalo = isDark
                    ? "rgba(12,27,42,0.75)"
                    : "rgba(255,255,255,0.85)";

                for (const layer of style.layers ?? []) {
                    const l = layer as {
                        id?: string;
                        layout?: Record<string, unknown>;
                        paint?: Record<string, unknown>;
                        type?: string;
                    };
                    if (l.type !== "symbol" || !l.layout?.["text-font"]) continue;

                    l.layout["text-font"] = ["PT Sans Regular"];

                    // Shields carry their own icon-based styling; recolouring
                    // their text would leave it unreadable on the shield.
                    if (/shield/i.test(l.id ?? "")) continue;

                    l.paint = {
                        ...l.paint,
                        "text-color": muted,
                        "text-halo-color": mutedHalo,
                        "text-halo-width": 1,
                    };
                }

                if (!cancelled) {
                    setMapStyle({ ...style, glyphs: GLYPHS_URL });
                }
            } catch {
                // Fall back to the untouched style: labels then use the
                // basemap's fonts rather than disappearing.
                if (!cancelled) setMapStyle(styleUrl);
            }
        })();

        return () => {
            cancelled = true;
        };
    }, [styleUrl, isDark]);

    // Uncontrolled camera (initialViewState + no `onMove` write-back) so
    // fitBounds can animate freely. A controlled viewState would be re-applied
    // by React on every frame and fight the easing.
    const [zoomLevel, setZoomLevel] = useState(10);

    const handleMove = useCallback((e: { viewState: { zoom: number } }) => {
        // Quantise: markers only care about whole zoom steps, so this re-renders
        // ~once per zoom level instead of once per animation frame.
        setZoomLevel((prev) => {
            const next = Math.floor(e.viewState.zoom);
            return next === prev ? prev : next;
        });
    }, []);

    /**
     * Register the pin icons. Re-run on every style load: swapping the
     * basemap (light/dark) replaces the style, and images do not survive it.
     */
    /**
     * Re-asserts our layers' stacking order.
     *
     * MapLibre paints `style.layers` in array order, and `addLayer` without a
     * `beforeId` appends to the end. Selecting a different route unmounts the
     * old `shape-<id>` source and mounts a new one, so the fresh line layer
     * lands on top of `route-stop-pin` -- which is never recreated, because
     * its own source is stable. The result was that stop pins painted above
     * the route on first load and below it after any route change.
     *
     * `beforeId` on the <Layer> would be the declarative fix, but it throws
     * when the referenced layer does not exist yet, and `route-stop-pin` is
     * conditional on zoom and on having stops. So instead the order is
     * restated here, after the fact, over whichever layers currently exist.
     */
    const enforceLayerOrder = useCallback(() => {
        const map = mapRef.current?.getMap?.();
        if (!map?.style) return;

        let order: string[];
        try {
            order = map.getLayersOrder();
        } catch {
            return;
        }

        // Bottom to top. Route lines first, then stop graphics above them,
        // and the invisible blockers last: symbol placement walks the array
        // backwards, so being last is what gives them collision priority
        // over the stop labels (see the layer's own comment).
        const desired = [
            ...order.filter((id) => id === "overview-line"),
            ...order.filter((id) => id.startsWith("shape-line")),
            ...order.filter((id) => id.startsWith("all-stops-")),
            ...order.filter((id) => id === "route-stop-pin"),
            ...order.filter((id) => id === "line-blockers-sym"),
        ];
        if (desired.length < 2) return;

        // Already correct when our layers occupy the tail of the array in
        // exactly this sequence. Checking first matters: `moveLayer` fires
        // `styledata`, which calls back into here, so moving unconditionally
        // would recurse until the stack blew.
        const tail = order.slice(-desired.length);
        if (tail.every((id, i) => id === desired[i])) return;

        // Moving each to the top in turn leaves them stacked in this order.
        for (const id of desired) {
            try {
                map.moveLayer(id);
            } catch {
                // A layer can disappear between the snapshot and this call
                // (route switch mid-flight); the next pass will fix it.
            }
        }
    }, []);

    const addPinImages = useCallback(() => {
        const map = mapRef.current?.getMap?.();
        if (!map) return;

        // Only add what is missing. `addImage`/`removeImage` themselves fire
        // `styledata`, so unconditionally re-registering here recursed until
        // the stack blew -- the page never finished loading.
        for (const [id, spec] of Object.entries(PIN_IMAGES)) {
            if (map.hasImage?.(id)) continue;
            map.addImage(id, makeDotImage(spec), { pixelRatio: 2 });
        }

        if (!map.hasImage?.("line-blocker")) {
            map.addImage("line-blocker", makeBlockerImage(), { pixelRatio: 2 });
        }
    }, []);

    /** Both style-level fixups, for `onLoad` and `onStyleData`. */
    const handleStyleReady = useCallback(() => {
        addPinImages();
        enforceLayerOrder();
    }, [addPinImages, enforceLayerOrder]);

    // Clustering is O(n^2); keep it out of the render path on every pan.
    const routeClusters = useMemo(
        () => clusterStops(routeStops, nearbyThreshold),
        [routeStops, nearbyThreshold]
    );

    /**
     * The lines labels must dodge: every drawn route, or the network overview
     * when nothing is selected. Memoised because the axis lookup below walks
     * these vertices once per stop.
     */
    const labelShapes = useMemo<ShapeCollection | null>(() => {
        if (layers.length) {
            return {
                type: "FeatureCollection",
                features: layers.flatMap((l) => l.geometry.features),
            };
        }
        return overview ?? null;
    }, [layers, overview]);

    /**
     * Collision footprint for those lines. Only built while stop labels are
     * on screen -- below that zoom there is nothing to push around, and the
     * point chain would be wasted work on every pan.
     */
    const blockers = useMemo(
        () =>
            zoomLevel >= labelThreshold && routeClusters.length > 0
                ? blockerPoints(labelShapes, zoomLevel)
                : { type: "FeatureCollection" as const, features: [] },
        [labelShapes, zoomLevel, labelThreshold, routeClusters.length]
    );

    // Ask for the stop layer the first time it could actually be shown, so a
    // visitor who never zooms in never downloads it.
    useEffect(() => {
        if (zoomLevel >= allStopsZoom) onNeedAllStops?.();
    }, [zoomLevel, allStopsZoom, onNeedAllStops]);

    /**
     * Restate the stacking order whenever the set of layers changes.
     *
     * `onStyleData` alone is not enough: react-map-gl adds a <Layer> during
     * React's commit, which does not necessarily emit `styledata` before the
     * next paint. The deps are exactly the things that mount or unmount one
     * of our layers. Deferred a frame so every sibling <Layer> in the same
     * commit has registered before the order is read.
     */
    useEffect(() => {
        const t = requestAnimationFrame(enforceLayerOrder);
        return () => cancelAnimationFrame(t);
    }, [
        enforceLayerOrder,
        layers,
        overview,
        allStops,
        zoomLevel,
        routeClusters.length,
        blockers.features.length,
    ]);

    // Union of every drawn layer, so a multi-route stop view frames them all.
    const bounds = useMemo(() => {
        const boxes = layers
            .map((l) => geometryBounds(l.geometry))
            .filter((b): b is [[number, number], [number, number]] =>
                Boolean(b)
            );
        if (!boxes.length) return null;

        return boxes.reduce(
            (acc, b) => [
                [Math.min(acc[0][0], b[0][0]), Math.min(acc[0][1], b[0][1])],
                [Math.max(acc[1][0], b[1][0]), Math.max(acc[1][1], b[1][1])],
            ],
            boxes[0]
        ) as LngLatBoundsLike;
    }, [layers]);

    /**
     * Centre a newly opened stop, zooming in only if we are further out than
     * `stopFocusZoom`.
     *
     * Always jumping to a fixed zoom would pull the camera *backwards* for
     * someone already examining the area at z17-18, so the zoom is only ever
     * raised, never lowered. Keyed on the stop's coordinates so re-rendering
     * the popup does not re-animate.
     */
    const stopFocusZoom = 16;
    const focusKey = activeStop
        ? `${activeStop.lat.toFixed(5)},${activeStop.lon.toFixed(5)}`
        : null;

    useEffect(() => {
        const map = mapRef.current;
        if (!map || !activeStop) return;

        map.easeTo({
            center: [activeStop.lon, activeStop.lat],
            zoom: Math.max(map.getZoom(), stopFocusZoom),
            duration: 600,
            essential: true,
        });
        // activeStop is a fresh object each render; focusKey is the real input.
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [focusKey, stopFocusRequest]);

    // Frame the selected route. Depends on `bounds` (not `geometry`) so
    // re-selecting a route with identical extent does not re-animate.
    useEffect(() => {
        const map = mapRef.current;
        if (!map || !bounds) return;

        map.fitBounds(bounds, {
            // Leaves room for the stop labels, which extend to the right of
            // their pin, and keeps the line clear of the zoom controls.
            padding: { top: 64, bottom: 64, left: 64, right: 96 },
            // A single stop would otherwise zoom to maxZoom.
            maxZoom: 15,
            duration: 900,
            essential: true,
        });
    }, [bounds]);

    return (
        <MapGL
            ref={mapRef}
            // Clicking a GPU circle layer: hit-test by layer id, since these
            // are painted pixels rather than DOM nodes with their own handlers.
            interactiveLayerIds={[
                ...(routeClusters.length ? ["route-stop-pin"] : []),
                ...(allStops && zoomLevel >= allStopsZoom
                    ? ["all-stops-circle"]
                    : []),
            ]}
            onClick={(e) => {
                const f = e.features?.[0];

                // Nothing under the cursor: treat it as "dismiss".
                //
                // `e.features` is populated from `interactiveLayerIds` only,
                // so an empty list means the click genuinely missed every
                // stop. MapLibre also suppresses `click` once the pointer
                // travels past `clickTolerance` (3px), so a drag-to-pan ends
                // in `dragend` rather than here -- panning cannot dismiss the
                // selection by accident.
                if (!f) {
                    onBackgroundClick?.();
                    return;
                }

                // Route stops carry the original stop, so the panel can
                // resolve the station exactly as a marker click used to.
                if (f.layer?.id === "route-stop-pin") {
                    const p = f.properties ?? {};
                    setStopFocusRequest((n) => n + 1);
                    onStopClick?.({
                        stop_id: String(p.stop_id ?? ""),
                        stop_name: String(p.stop_name ?? p.name ?? ""),
                        stop_lat: Number(p.lat),
                        stop_lon: Number(p.lon),
                        sequence: 0,
                    });
                    return;
                }

                if (f.layer?.id === "all-stops-circle") {
                    const [lon, lat] = (f.geometry as Point).coordinates;
                    setStopFocusRequest((n) => n + 1);
                    onStationClick?.(
                        String(f.properties?.name ?? ""),
                        lat,
                        lon
                    );
                }
            }}
            onMouseMove={(e) => {
                const f = e.features?.[0];
                const id = f?.layer?.id;
                const name =
                    id === "all-stops-circle" || id === "route-stop-pin"
                        ? String(f?.properties?.name ?? "")
                        : null;
                // Only re-render when the hovered stop actually changes;
                // mousemove fires on every pointer pixel.
                setHoveredStop((prev) => (prev === name ? prev : name));
            }}
            onMouseLeave={() => setHoveredStop(null)}
            cursor={hoveredStop ? "pointer" : "auto"}
            initialViewState={{
                latitude: -6.1907,
                longitude: 106.8228,
                zoom: 10,
            }}
            onMove={handleMove}
            onLoad={handleStyleReady}
            onStyleData={handleStyleReady}
            // Fills whatever the parent allots. A hard 100vh would overflow the
            // mobile layout, where the map shares the screen with a bottom sheet.
            style={{ width: "100%", height: "100%" }}
            mapStyle={mapStyle}
        >
            <NavigationControl position="bottom-right" />

            {/*
              The whole network, faint, as context. One GPU-rendered GeoJSON
              source -- not 240 React layers. Hidden once a route or stop is
              selected so the selection reads clearly.
            */}
            {overview && layers.length === 0 && (
                <Source id="overview" type="geojson" data={overview}>
                    <Layer
                        id="overview-line"
                        type="line"
                        layout={{ "line-join": "round", "line-cap": "round" }}
                        paint={{
                            // Colour travels in the feature, so all 700 lines
                            // stay a single draw call.
                            "line-color": ["get", "color"],
                            "line-opacity": 0.35,
                            // Thinner when zoomed out, where lines bunch up.
                            "line-width": [
                                "interpolate",
                                ["linear"],
                                ["zoom"],
                                9,
                                1,
                                13,
                                2.5,
                            ],
                        }}
                    />
                </Source>
            )}

            {/* A Source per route so each keeps its own colour. */}
            {layers.length === 0 ? (
                <Source id="shape-empty" type="geojson" data={EMPTY_GEOJSON}>
                    <Layer id="shape-line" type="line" />
                </Source>
            ) : (
                layers.map((l) => (
                    <Source
                        key={l.id}
                        id={`shape-${l.id}`}
                        type="geojson"
                        data={l.geometry}
                    >
                        <Layer
                            id={`shape-line-${l.id}`}
                            type="line"
                            layout={{
                                "line-join": "round",
                                "line-cap": "round",
                            }}
                            paint={{
                                "line-color": `#${l.color}`,
                                "line-width": 3,
                                // Slight transparency so overlapping corridors
                                // stay legible when many routes share a street.
                                "line-opacity": layers.length > 1 ? 0.75 : 1,
                            }}
                        />
                    </Source>
                ))
            )}

            {/*
              All stops, GPU-rendered. Only above `allStopsZoom`, where pins
              are far enough apart to read. 6,437 DOM markers would instead be
              6,437 React components plus an O(n^2) clustering pass.
            */}
            {allStops && zoomLevel >= allStopsZoom && (
                <Source id="all-stops" type="geojson" data={allStops}>
                    {/*
                      Dot and label are one symbol here too, for the same
                      reason as the route stops: a circle layer is invisible to
                      the collision engine, so labels used to settle underneath
                      neighbouring dots. The icon carries the collision box.
                    */}
                    <Layer
                        id="all-stops-circle"
                        type="symbol"
                        layout={{
                            "icon-image": [
                                "case",
                                ["==", ["get", "name"], hoveredStop ?? "\u0000"],
                                "all-stop-dot-hover",
                                "all-stop-dot",
                            ],
                            "icon-allow-overlap": true,
                            "icon-ignore-placement": false,
                            // Grows with zoom, anchored so the dot is still a
                            // usable tap target at the zoom it first appears:
                            // ~7.4px across at z12, ~15px at z17. Extending
                            // the original 14->17 ramp backwards instead would
                            // have put z12 at 5.2px, which is the
                            // too-small-to-hit problem all over again.
                            "icon-size": [
                                "interpolate",
                                ["linear"],
                                ["zoom"],
                                12,
                                0.62,
                                17,
                                1.25,
                            ],
                            // Keeps the hover swap from being dropped by the
                            // collision index when dots are dense.
                            "icon-padding": 0,
                        }}
                        paint={{ "icon-opacity": 0.9 }}
                    />
                    <Layer
                        id="all-stops-label"
                        type="symbol"
                        // Deliberately higher than the dot's own floor of 12.
                        // Showing names from z12 meant ~330 labels competing
                        // across the whole city at once; the dots read as a
                        // network at that scale, the names only become useful
                        // once you are zoomed into a neighbourhood.
                        minzoom={14}
                        layout={{
                            "text-field": ["get", "name"],
                            "text-font": LABEL_FONT,
                            "text-size": 11,
                            "text-max-width": 8,
                            // Same dodge-then-hide behaviour as the route
                            // labels, rather than a fixed offset below the pin.
                            "text-variable-anchor": [
                                "left",
                                "right",
                                "top",
                                "bottom",
                                "top-left",
                                "top-right",
                                "bottom-left",
                                "bottom-right",
                            ],
                            "text-radial-offset": 0.8,
                            "text-justify": "auto",
                            "text-allow-overlap": false,
                            // Busier interchanges win when labels collide.
                            "symbol-sort-key": ["-", 0, ["get", "routes"]],
                        }}
                        paint={{
                            "text-color": "#0C1B2A",
                            "text-halo-color": "#FFFFFF",
                            "text-halo-width": 1.5,
                        }}
                    />
                </Source>
            )}

            {zoomLevel > zoomThreshold && routeClusters.length > 0 && (
                <StopMarkers
                    clusters={routeClusters}
                    activeName={activeStop?.name ?? null}
                    hoveredName={hoveredStop}
                    showLabels={zoomLevel >= labelThreshold}
                    textFont={LABEL_FONT}
                    shapes={labelShapes}
                />
            )}

            {/*
              Invisible collision footprint for the route line.

              Declared AFTER the stop labels on purpose: MapLibre places
              symbol layers in reverse style order (`pauseable_placement.ts`
              walks `order.length - 1` down to 0), so a layer listed later
              claims its collision space first. These blockers are therefore
              already in the index when the labels look for a free anchor,
              which is what makes "do not sit on the route" actually binding.

              The icon is a 1x1 transparent pixel scaled by `icon-size`; only
              the collision box matters, nothing is drawn.
            */}
            {blockers.features.length > 0 && (
                <Source id="line-blockers" type="geojson" data={blockers}>
                    <Layer
                        id="line-blockers-sym"
                        type="symbol"
                        layout={{
                            "icon-image": "line-blocker",
                            "icon-size": 1,
                            "icon-allow-overlap": true,
                            "icon-ignore-placement": false,
                            "icon-padding": 0,
                        }}
                        paint={{ "icon-opacity": 0 }}
                    />
                </Source>
            )}

            {/*
              Station card, anchored to the stop it describes. `anchor="bottom"`
              puts the card above the point with MapLibre's own tip pointing
              down at it, which is why the popup is used rather than a plain
              absolutely-positioned div.
            */}
            {activeStop && stopPopup && (
                <Popup
                    longitude={activeStop.lon}
                    latitude={activeStop.lat}
                    anchor="bottom"
                    offset={14}
                    closeButton={false}
                    closeOnClick={false}
                    maxWidth="none"
                    className="transum-stop-popup"
                >
                    {stopPopup}
                </Popup>
            )}
        </MapGL>
    );
};

export default MainMapComponent;
